// User
export const ERROR_RECEIVE_USER = 'ERROR_RECEIVE_USER';
export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';

export const ERROR_SIGN_IN = 'ERROR_SIGN_IN';
export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN';
export const SUCCESS_SIGN_IN = 'SUCCESS_SIGN_IN';

export const ERROR_SIGN_UP = 'ERROR_SIGN_UP';
export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP';
export const SUCCESS_SIGN_UP = 'SUCCESS_SIGN_UP';

export const REQUEST_SIGN_OUT = 'REQUEST_SIGN_OUT';


// Photo
export const ERROR_RECEIVE_PHOTO = 'ERROR_RECEIVE_PHOTO';
export const REQUEST_PHOTO = 'REQUEST_PHOTO';
export const RECEIVE_PHOTO = 'RECEIVE_PHOTO';

export const ERROR_UPLOAD_PHOTO = 'ERROR_UPLOAD_PHOTO';
export const REQUEST_UPLOAD_PHOTO = 'REQUEST_UPLOAD_PHOTO';
export const SUCCESS_UPLOAD_PHOTO = 'SUCCESS_UPLOAD_PHOTO';

export const ERROR_DELETE_PHOTO = 'ERROR_DELETE_PHOTO';
export const REQUEST_DELETE_PHOTO = 'REQUEST_DELETE_PHOTO';
export const SUCCESS_DELETE_PHOTO = 'SUCCESS_DELETE_PHOTO';

export const ERROR_RECEIVE_PHOTOS_PAGINATION = 'ERROR_RECEIVE_PHOTOS_PAGINATION';
export const REQUEST_PHOTOS_PAGINATION = 'REQUEST_PHOTOS_PAGINATION';
export const RECEIVE_PHOTOS_PAGINATION = 'RECEIVE_PHOTOS_PAGINATION';

export const ERROR_UPDATE_PHOTO = 'ERROR_UPDATE_PHOTO';
export const REQUEST_UPDATE_PHOTO = 'REQUEST_UPDATE_PHOTO';
export const SUCCESS_UPDATE_PHOTO = 'SUCCESS_UPDATE_PHOTO';


